name: Unit Tests

on:
  push:
    branches: [ "swo" ]
  pull_request:
    branches: [ "swo" ]

jobs:
  unittests:
    runs-on: ubuntu-latest
    container:
      image: kirschbaumdevelopment/laravel-test-runner:8.0

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install composer dependencies
        run: |
          composer config --no-plugins allow-plugins.php-http/discovery false
          composer install --no-interaction --prefer-dist

      - name: Run Testsuite        
        run: vendor/bin/phpunit tests/
